"use strict";
console.log("Combine class");
var classArr = ["Adnan", "Asif", "Shafi", "Ghani", "Sajjad"];
var newArr = classArr.slice(1, 3);
console.log(newArr);
console.log(classArr);
classArr.push("Asiff");
console.log(classArr.push("Asifi"));
console.log(classArr);
console.log(...classArr);
